name: Linux

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    if: "!contains(github.event.head_commit.message, '[ci skip]')"

    steps:

    - name: Set up Go
      uses: actions/setup-go@v2.1.4
      with:
        go-version: 1.17
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Basic build
      run: go build ./cmd/...

    - name: Get QEMU
      run: |
        # The qemu in Ubuntu 20.04 (Focal) is too old; we need 5.x something
        # to run Go binaries. 5.2.0 (Debian bullseye) empirically works, and
        # use this PPA which brings in a modern qemu.
        sudo add-apt-repository -y ppa:jacob/virtualisation
        sudo apt-get -y update
        sudo apt-get -y install qemu-user

    - name: Run tests on linux
      run: go test -bench=. -benchtime=1x ./...

    - uses: k0kubun/action-slack@v2.0.0
      with:
        payload: |
          {
            "attachments": [{
              "text": "${{ job.status }}: ${{ github.workflow }} <https://github.com/${{ github.repository }}/commit/${{ github.sha }}/checks|${{ env.COMMIT_DATE }} #${{ env.COMMIT_NUMBER_OF_DAY }}> " +
                      "(<https://github.com/${{ github.repository }}/commit/${{ github.sha }}|" + "${{ github.sha }}".substring(0, 10) + ">) " +
                      "of ${{ github.repository }}@" + "${{ github.ref }}".split('/').reverse()[0] + " by ${{ github.event.head_commit.committer.name }}",
              "color": "danger"
            }]
          }
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      if: failure() && github.event_name == 'push'

